import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :app_web, AppWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, :api_client, App.Finch

# Do not print debug messages in production
config :logger, level: :info

# ## Error reporting
#
# Configure errors to be reported to Sentry. Requires to call `plug Sentry.PlugContext`
# in the Endpoint.
# According to the Sentry documentation, the `:dsn` is "safe to keep public because they
# only allow submission of new events and related event data; they do not allow read
# access to any information".
#
# See the documentation of `:sentry` for more information.

config :sentry,
  dsn: "https://001afba5be1f4c968de015c2fc051cd9@o1240316.ingest.sentry.io/6392357",
  environment_name: :prod,
  enable_source_code_context: true,
  root_source_code_path: File.cwd!(),
  tags: %{
    env: "production"
  },
  included_environments: [:prod]

config :logger,
  backends: [:console, Sentry.LoggerBackend]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
