name: Dockerfile CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: Validate Dockerfile
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            Dockerfile:
              - 'Dockerfile'
      - name: Build Dockerfile
        if: steps.changes.outputs.Dockerfile == 'true'
        run: docker build .
